/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: ProductId;
    name: string;
    description: string;
    concerns: Array<string>;
    imageUrl: string;
    skinType: SkinType;
    category: ProductCategory;
    brand: string;
    price: Price;
    keyIngredients: Array<string>;
    usageInstructions: string;
}
export interface Price {
    currency: Currency;
    amount: number;
}
export interface ProductUpdate {
    name?: string;
    description?: string;
    concerns?: Array<string>;
    imageUrl?: string;
    skinType?: SkinType;
    category?: ProductCategory;
    brand?: string;
    price?: Price;
    keyIngredients?: Array<string>;
    usageInstructions?: string;
}
export type Currency = {
    __kind__: "eur";
    eur: null;
} | {
    __kind__: "gbp";
    gbp: null;
} | {
    __kind__: "jpy";
    jpy: null;
} | {
    __kind__: "usd";
    usd: null;
} | {
    __kind__: "other";
    other: string;
};
export type ProductId = bigint;
export type ProductCategory = {
    __kind__: "sunscreen";
    sunscreen: null;
} | {
    __kind__: "toner";
    toner: null;
} | {
    __kind__: "cleanser";
    cleanser: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "mask";
    mask: null;
} | {
    __kind__: "exfoliator";
    exfoliator: null;
} | {
    __kind__: "serum";
    serum: null;
} | {
    __kind__: "eyeTreatment";
    eyeTreatment: null;
} | {
    __kind__: "moisturizer";
    moisturizer: null;
};
export interface UserProfile {
    skinConcerns: Array<string>;
    name: string;
    skinType?: SkinType;
}
export interface ProductFilter {
    concerns?: string;
    maxPrice?: number;
    searchText?: string;
    currency?: Currency;
    skinType?: SkinType;
    category?: ProductCategory;
    minPrice?: number;
}
export enum SkinType {
    dry = "dry",
    combination = "combination",
    normal = "normal",
    oily = "oily",
    sensitive = "sensitive"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(product: Product): Promise<ProductId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteProduct(id: ProductId): Promise<void>;
    filterProducts(filters: ProductFilter): Promise<Array<Product>>;
    getAllCategories(): Promise<Array<ProductCategory>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProductById(id: ProductId): Promise<Product | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeActor(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    resetProducts(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateProduct(id: ProductId, productUpdate: ProductUpdate): Promise<void>;
}
import type { Currency as _Currency, Price as _Price, Product as _Product, ProductCategory as _ProductCategory, ProductFilter as _ProductFilter, ProductId as _ProductId, ProductUpdate as _ProductUpdate, SkinType as _SkinType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_Product_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_Product_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async filterProducts(arg0: ProductFilter): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterProducts(to_candid_ProductFilter_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterProducts(to_candid_ProductFilter_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCategories(): Promise<Array<ProductCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductById(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeActor(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeActor();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeActor();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resetProducts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetProducts();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProduct(arg0: ProductId, arg1: ProductUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_ProductUpdate_n36(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_ProductUpdate_n36(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Currency_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Currency): Currency {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Price_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Price): Price {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_SkinType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkinType): SkinType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SkinType]): SkinType | null {
    return value.length === 0 ? null : from_candid_SkinType_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    name: string;
    description: string;
    concerns: Array<string>;
    imageUrl: string;
    skinType: _SkinType;
    category: _ProductCategory;
    brand: string;
    price: _Price;
    keyIngredients: Array<string>;
    usageInstructions: string;
}): {
    id: ProductId;
    name: string;
    description: string;
    concerns: Array<string>;
    imageUrl: string;
    skinType: SkinType;
    category: ProductCategory;
    brand: string;
    price: Price;
    keyIngredients: Array<string>;
    usageInstructions: string;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        concerns: value.concerns,
        imageUrl: value.imageUrl,
        skinType: from_candid_SkinType_n18(_uploadFile, _downloadFile, value.skinType),
        category: from_candid_ProductCategory_n20(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        price: from_candid_Price_n22(_uploadFile, _downloadFile, value.price),
        keyIngredients: value.keyIngredients,
        usageInstructions: value.usageInstructions
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currency: _Currency;
    amount: number;
}): {
    currency: Currency;
    amount: number;
} {
    return {
        currency: from_candid_Currency_n24(_uploadFile, _downloadFile, value.currency),
        amount: value.amount
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    skinConcerns: Array<string>;
    name: string;
    skinType: [] | [_SkinType];
}): {
    skinConcerns: Array<string>;
    name: string;
    skinType?: SkinType;
} {
    return {
        skinConcerns: value.skinConcerns,
        name: value.name,
        skinType: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.skinType))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dry: null;
} | {
    combination: null;
} | {
    normal: null;
} | {
    oily: null;
} | {
    sensitive: null;
}): SkinType {
    return "dry" in value ? SkinType.dry : "combination" in value ? SkinType.combination : "normal" in value ? SkinType.normal : "oily" in value ? SkinType.oily : "sensitive" in value ? SkinType.sensitive : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sunscreen: null;
} | {
    toner: null;
} | {
    cleanser: null;
} | {
    other: string;
} | {
    mask: null;
} | {
    exfoliator: null;
} | {
    serum: null;
} | {
    eyeTreatment: null;
} | {
    moisturizer: null;
}): {
    __kind__: "sunscreen";
    sunscreen: null;
} | {
    __kind__: "toner";
    toner: null;
} | {
    __kind__: "cleanser";
    cleanser: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "mask";
    mask: null;
} | {
    __kind__: "exfoliator";
    exfoliator: null;
} | {
    __kind__: "serum";
    serum: null;
} | {
    __kind__: "eyeTreatment";
    eyeTreatment: null;
} | {
    __kind__: "moisturizer";
    moisturizer: null;
} {
    return "sunscreen" in value ? {
        __kind__: "sunscreen",
        sunscreen: value.sunscreen
    } : "toner" in value ? {
        __kind__: "toner",
        toner: value.toner
    } : "cleanser" in value ? {
        __kind__: "cleanser",
        cleanser: value.cleanser
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "mask" in value ? {
        __kind__: "mask",
        mask: value.mask
    } : "exfoliator" in value ? {
        __kind__: "exfoliator",
        exfoliator: value.exfoliator
    } : "serum" in value ? {
        __kind__: "serum",
        serum: value.serum
    } : "eyeTreatment" in value ? {
        __kind__: "eyeTreatment",
        eyeTreatment: value.eyeTreatment
    } : "moisturizer" in value ? {
        __kind__: "moisturizer",
        moisturizer: value.moisturizer
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eur: null;
} | {
    gbp: null;
} | {
    jpy: null;
} | {
    usd: null;
} | {
    other: string;
}): {
    __kind__: "eur";
    eur: null;
} | {
    __kind__: "gbp";
    gbp: null;
} | {
    __kind__: "jpy";
    jpy: null;
} | {
    __kind__: "usd";
    usd: null;
} | {
    __kind__: "other";
    other: string;
} {
    return "eur" in value ? {
        __kind__: "eur",
        eur: value.eur
    } : "gbp" in value ? {
        __kind__: "gbp",
        gbp: value.gbp
    } : "jpy" in value ? {
        __kind__: "jpy",
        jpy: value.jpy
    } : "usd" in value ? {
        __kind__: "usd",
        usd: value.usd
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductCategory>): Array<ProductCategory> {
    return value.map((x)=>from_candid_ProductCategory_n20(_uploadFile, _downloadFile, x));
}
function to_candid_Currency_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): _Currency {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Price_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Price): _Price {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ProductFilter_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductFilter): _ProductFilter {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_ProductUpdate_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductUpdate): _ProductUpdate {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SkinType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkinType): _SkinType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    concerns?: string;
    maxPrice?: number;
    searchText?: string;
    currency?: Currency;
    skinType?: SkinType;
    category?: ProductCategory;
    minPrice?: number;
}): {
    concerns: [] | [string];
    maxPrice: [] | [number];
    searchText: [] | [string];
    currency: [] | [_Currency];
    skinType: [] | [_SkinType];
    category: [] | [_ProductCategory];
    minPrice: [] | [number];
} {
    return {
        concerns: value.concerns ? candid_some(value.concerns) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        searchText: value.searchText ? candid_some(value.searchText) : candid_none(),
        currency: value.currency ? candid_some(to_candid_Currency_n9(_uploadFile, _downloadFile, value.currency)) : candid_none(),
        skinType: value.skinType ? candid_some(to_candid_SkinType_n3(_uploadFile, _downloadFile, value.skinType)) : candid_none(),
        category: value.category ? candid_some(to_candid_ProductCategory_n5(_uploadFile, _downloadFile, value.category)) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProductId;
    name: string;
    description: string;
    concerns: Array<string>;
    imageUrl: string;
    skinType: SkinType;
    category: ProductCategory;
    brand: string;
    price: Price;
    keyIngredients: Array<string>;
    usageInstructions: string;
}): {
    id: _ProductId;
    name: string;
    description: string;
    concerns: Array<string>;
    imageUrl: string;
    skinType: _SkinType;
    category: _ProductCategory;
    brand: string;
    price: _Price;
    keyIngredients: Array<string>;
    usageInstructions: string;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        concerns: value.concerns,
        imageUrl: value.imageUrl,
        skinType: to_candid_SkinType_n3(_uploadFile, _downloadFile, value.skinType),
        category: to_candid_ProductCategory_n5(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        price: to_candid_Price_n7(_uploadFile, _downloadFile, value.price),
        keyIngredients: value.keyIngredients,
        usageInstructions: value.usageInstructions
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    skinConcerns: Array<string>;
    name: string;
    skinType?: SkinType;
}): {
    skinConcerns: Array<string>;
    name: string;
    skinType: [] | [_SkinType];
} {
    return {
        skinConcerns: value.skinConcerns,
        name: value.name,
        skinType: value.skinType ? candid_some(to_candid_SkinType_n3(_uploadFile, _downloadFile, value.skinType)) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name?: string;
    description?: string;
    concerns?: Array<string>;
    imageUrl?: string;
    skinType?: SkinType;
    category?: ProductCategory;
    brand?: string;
    price?: Price;
    keyIngredients?: Array<string>;
    usageInstructions?: string;
}): {
    name: [] | [string];
    description: [] | [string];
    concerns: [] | [Array<string>];
    imageUrl: [] | [string];
    skinType: [] | [_SkinType];
    category: [] | [_ProductCategory];
    brand: [] | [string];
    price: [] | [_Price];
    keyIngredients: [] | [Array<string>];
    usageInstructions: [] | [string];
} {
    return {
        name: value.name ? candid_some(value.name) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        concerns: value.concerns ? candid_some(value.concerns) : candid_none(),
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        skinType: value.skinType ? candid_some(to_candid_SkinType_n3(_uploadFile, _downloadFile, value.skinType)) : candid_none(),
        category: value.category ? candid_some(to_candid_ProductCategory_n5(_uploadFile, _downloadFile, value.category)) : candid_none(),
        brand: value.brand ? candid_some(value.brand) : candid_none(),
        price: value.price ? candid_some(to_candid_Price_n7(_uploadFile, _downloadFile, value.price)) : candid_none(),
        keyIngredients: value.keyIngredients ? candid_some(value.keyIngredients) : candid_none(),
        usageInstructions: value.usageInstructions ? candid_some(value.usageInstructions) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currency: Currency;
    amount: number;
}): {
    currency: _Currency;
    amount: number;
} {
    return {
        currency: to_candid_Currency_n9(_uploadFile, _downloadFile, value.currency),
        amount: value.amount
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "eur";
    eur: null;
} | {
    __kind__: "gbp";
    gbp: null;
} | {
    __kind__: "jpy";
    jpy: null;
} | {
    __kind__: "usd";
    usd: null;
} | {
    __kind__: "other";
    other: string;
}): {
    eur: null;
} | {
    gbp: null;
} | {
    jpy: null;
} | {
    usd: null;
} | {
    other: string;
} {
    return value.__kind__ === "eur" ? {
        eur: value.eur
    } : value.__kind__ === "gbp" ? {
        gbp: value.gbp
    } : value.__kind__ === "jpy" ? {
        jpy: value.jpy
    } : value.__kind__ === "usd" ? {
        usd: value.usd
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkinType): {
    dry: null;
} | {
    combination: null;
} | {
    normal: null;
} | {
    oily: null;
} | {
    sensitive: null;
} {
    return value == SkinType.dry ? {
        dry: null
    } : value == SkinType.combination ? {
        combination: null
    } : value == SkinType.normal ? {
        normal: null
    } : value == SkinType.oily ? {
        oily: null
    } : value == SkinType.sensitive ? {
        sensitive: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "sunscreen";
    sunscreen: null;
} | {
    __kind__: "toner";
    toner: null;
} | {
    __kind__: "cleanser";
    cleanser: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "mask";
    mask: null;
} | {
    __kind__: "exfoliator";
    exfoliator: null;
} | {
    __kind__: "serum";
    serum: null;
} | {
    __kind__: "eyeTreatment";
    eyeTreatment: null;
} | {
    __kind__: "moisturizer";
    moisturizer: null;
}): {
    sunscreen: null;
} | {
    toner: null;
} | {
    cleanser: null;
} | {
    other: string;
} | {
    mask: null;
} | {
    exfoliator: null;
} | {
    serum: null;
} | {
    eyeTreatment: null;
} | {
    moisturizer: null;
} {
    return value.__kind__ === "sunscreen" ? {
        sunscreen: value.sunscreen
    } : value.__kind__ === "toner" ? {
        toner: value.toner
    } : value.__kind__ === "cleanser" ? {
        cleanser: value.cleanser
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "mask" ? {
        mask: value.mask
    } : value.__kind__ === "exfoliator" ? {
        exfoliator: value.exfoliator
    } : value.__kind__ === "serum" ? {
        serum: value.serum
    } : value.__kind__ === "eyeTreatment" ? {
        eyeTreatment: value.eyeTreatment
    } : value.__kind__ === "moisturizer" ? {
        moisturizer: value.moisturizer
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
