/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const SkinType = IDL.Variant({
  'dry' : IDL.Null,
  'combination' : IDL.Null,
  'normal' : IDL.Null,
  'oily' : IDL.Null,
  'sensitive' : IDL.Null,
});
export const ProductCategory = IDL.Variant({
  'sunscreen' : IDL.Null,
  'toner' : IDL.Null,
  'cleanser' : IDL.Null,
  'other' : IDL.Text,
  'mask' : IDL.Null,
  'exfoliator' : IDL.Null,
  'serum' : IDL.Null,
  'eyeTreatment' : IDL.Null,
  'moisturizer' : IDL.Null,
});
export const Currency = IDL.Variant({
  'eur' : IDL.Null,
  'gbp' : IDL.Null,
  'jpy' : IDL.Null,
  'usd' : IDL.Null,
  'other' : IDL.Text,
});
export const Price = IDL.Record({
  'currency' : Currency,
  'amount' : IDL.Float64,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'concerns' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'skinType' : SkinType,
  'category' : ProductCategory,
  'brand' : IDL.Text,
  'price' : Price,
  'keyIngredients' : IDL.Vec(IDL.Text),
  'usageInstructions' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductFilter = IDL.Record({
  'concerns' : IDL.Opt(IDL.Text),
  'maxPrice' : IDL.Opt(IDL.Float64),
  'searchText' : IDL.Opt(IDL.Text),
  'currency' : IDL.Opt(Currency),
  'skinType' : IDL.Opt(SkinType),
  'category' : IDL.Opt(ProductCategory),
  'minPrice' : IDL.Opt(IDL.Float64),
});
export const UserProfile = IDL.Record({
  'skinConcerns' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'skinType' : IDL.Opt(SkinType),
});
export const ProductUpdate = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'concerns' : IDL.Opt(IDL.Vec(IDL.Text)),
  'imageUrl' : IDL.Opt(IDL.Text),
  'skinType' : IDL.Opt(SkinType),
  'category' : IDL.Opt(ProductCategory),
  'brand' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(Price),
  'keyIngredients' : IDL.Opt(IDL.Vec(IDL.Text)),
  'usageInstructions' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [ProductId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'filterProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(ProductCategory)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeActor' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetProducts' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func([ProductId, ProductUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const SkinType = IDL.Variant({
    'dry' : IDL.Null,
    'combination' : IDL.Null,
    'normal' : IDL.Null,
    'oily' : IDL.Null,
    'sensitive' : IDL.Null,
  });
  const ProductCategory = IDL.Variant({
    'sunscreen' : IDL.Null,
    'toner' : IDL.Null,
    'cleanser' : IDL.Null,
    'other' : IDL.Text,
    'mask' : IDL.Null,
    'exfoliator' : IDL.Null,
    'serum' : IDL.Null,
    'eyeTreatment' : IDL.Null,
    'moisturizer' : IDL.Null,
  });
  const Currency = IDL.Variant({
    'eur' : IDL.Null,
    'gbp' : IDL.Null,
    'jpy' : IDL.Null,
    'usd' : IDL.Null,
    'other' : IDL.Text,
  });
  const Price = IDL.Record({ 'currency' : Currency, 'amount' : IDL.Float64 });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'concerns' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'skinType' : SkinType,
    'category' : ProductCategory,
    'brand' : IDL.Text,
    'price' : Price,
    'keyIngredients' : IDL.Vec(IDL.Text),
    'usageInstructions' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductFilter = IDL.Record({
    'concerns' : IDL.Opt(IDL.Text),
    'maxPrice' : IDL.Opt(IDL.Float64),
    'searchText' : IDL.Opt(IDL.Text),
    'currency' : IDL.Opt(Currency),
    'skinType' : IDL.Opt(SkinType),
    'category' : IDL.Opt(ProductCategory),
    'minPrice' : IDL.Opt(IDL.Float64),
  });
  const UserProfile = IDL.Record({
    'skinConcerns' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'skinType' : IDL.Opt(SkinType),
  });
  const ProductUpdate = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'concerns' : IDL.Opt(IDL.Vec(IDL.Text)),
    'imageUrl' : IDL.Opt(IDL.Text),
    'skinType' : IDL.Opt(SkinType),
    'category' : IDL.Opt(ProductCategory),
    'brand' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(Price),
    'keyIngredients' : IDL.Opt(IDL.Vec(IDL.Text)),
    'usageInstructions' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [ProductId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'filterProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(ProductCategory)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeActor' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetProducts' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func([ProductId, ProductUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };