/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Currency = { 'eur' : null } |
  { 'gbp' : null } |
  { 'jpy' : null } |
  { 'usd' : null } |
  { 'other' : string };
export interface Price { 'currency' : Currency, 'amount' : number }
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'concerns' : Array<string>,
  'imageUrl' : string,
  'skinType' : SkinType,
  'category' : ProductCategory,
  'brand' : string,
  'price' : Price,
  'keyIngredients' : Array<string>,
  'usageInstructions' : string,
}
export type ProductCategory = { 'sunscreen' : null } |
  { 'toner' : null } |
  { 'cleanser' : null } |
  { 'other' : string } |
  { 'mask' : null } |
  { 'exfoliator' : null } |
  { 'serum' : null } |
  { 'eyeTreatment' : null } |
  { 'moisturizer' : null };
export interface ProductFilter {
  'concerns' : [] | [string],
  'maxPrice' : [] | [number],
  'searchText' : [] | [string],
  'currency' : [] | [Currency],
  'skinType' : [] | [SkinType],
  'category' : [] | [ProductCategory],
  'minPrice' : [] | [number],
}
export type ProductId = bigint;
export interface ProductUpdate {
  'name' : [] | [string],
  'description' : [] | [string],
  'concerns' : [] | [Array<string>],
  'imageUrl' : [] | [string],
  'skinType' : [] | [SkinType],
  'category' : [] | [ProductCategory],
  'brand' : [] | [string],
  'price' : [] | [Price],
  'keyIngredients' : [] | [Array<string>],
  'usageInstructions' : [] | [string],
}
export type SkinType = { 'dry' : null } |
  { 'combination' : null } |
  { 'normal' : null } |
  { 'oily' : null } |
  { 'sensitive' : null };
export interface UserProfile {
  'skinConcerns' : Array<string>,
  'name' : string,
  'skinType' : [] | [SkinType],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], ProductId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'filterProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'getAllCategories' : ActorMethod<[], Array<ProductCategory>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeActor' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetProducts' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<[ProductId, ProductUpdate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];